InputWebApp/ViewComponents/DropdownUserViewComponent.cs
using InputWebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace InputWebApp.ViewComponents
{
    public class DropdownUserViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var user = (ClaimsIdentity)User.Identity;
            string uname = user.Name;
            if (string.IsNullOrEmpty(uname))
            {
                uname = "test";
            }
            DropdownUserViewModel vm = new DropdownUserViewModel { Username = uname };
            return View(vm);

            //if (!string.IsNullOrEmpty(uname))
            //    return View(vm);
            //else
            //    return View("Empty");

            //return View();
        }
    }
}

InputWebApp/ViewComponents/MainMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InputWebApp.ViewComponents
{
    public class MainMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            //var user = (ClaimsIdentity)User.Identity;
            //string uname = user.Name;
            //DropdownUserViewModel vm = new DropdownUserViewModel { Username = uname };
            //if (!string.IsNullOrEmpty(uname))
            //    return View(vm);
            //else
            //    return View("Empty");

            return View();
        }
    }
}

InputWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InputWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InputWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InputWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - InputWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InputWebApp/Views/Shared/_LayoutCommon.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AI-Chatbot</title>
    @* <title>@ViewData["Title"] - InputWebApp</title> *@


    <link rel="apple-touch-icon" href="~/template-asset/app-assets/images/ico/apple-icon-120.png" />
    <link rel="shortcut icon" type="image/x-icon" href="~/template-asset/app-assets/images/ico/favicon.ico" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i%7COpen+Sans:300,300i,400,400i,600,600i,700,700i" rel="stylesheet" />
    <!-- BEGIN VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/css/vendors.css" />
    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/vendors/css/extensions/unslider.css" />
    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/vendors/css/weather-icons/climacons.min.css" />

    <link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/22.1.6/css/dx.common.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/22.1.6/css/dx.light.css" />

    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/fonts/meteocons/style.css" />
    @*<link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/vendors/css/charts/morris.css" />*@
    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/vendors/css/forms/selects/select2.min.css" />
    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/vendors/css/tables/jsgrid/jsgrid-theme.min.css" />
    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/vendors/css/tables/jsgrid/jsgrid.min.css" />
    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/vendors/css/tables/datatable/datatables.min.css" />
    <!-- END VENDOR CSS-->
    <!-- BEGIN STACK CSS-->
    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/css/app.css" />
    <!-- END STACK CSS-->
    <!-- BEGIN Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/css/core/menu/menu-types/vertical-menu.css" />
    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/css/core/colors/palette-gradient.css" />
    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/fonts/simple-line-icons/style.css" />
    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/css/core/colors/palette-gradient.css" />
    <link rel="stylesheet" type="text/css" href="~/template-asset/app-assets/css/pages/timeline.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/owl-carousel/css/owl.carousel.min.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/owl-carousel/css/owl.theme.default.min.css" />
    <!-- END Page Level CSS-->
    <!-- BEGIN Custom CSS-->
    @*<link rel="stylesheet" href="https://js.arcgis.com/4.22/esri/themes/light/main.css" />*@
    @RenderSection("Css", required: false)
    <link rel="stylesheet" type="text/css" href="~/template-asset/assets/css/style.css" />
</head>
<body class="vertical-layout vertical-menu 2-columns menu-expanded fixed-navbar" data-open="click" data-menu="vertical-menu" data-col="2-columns">
    <nav class="header-navbar navbar-expand-md navbar navbar-with-menu fixed-top navbar-dark navbar-shadow">
        <div class="navbar-wrapper">
            <div class="navbar-header">
                <ul class="nav navbar-nav flex-row">
                    <li class="nav-item mobile-menu d-md-none mr-auto">
                        <a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#">
                            <i class="ft-menu font-large-1"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" asp-area="" asp-controller="home" asp-action="index">
                            <img class="brand-logo"
                                 alt="stack admin logo"
                                 src="~/template-asset/app-assets/images/logo/stack-logo-light.png" />
                            <h2 class="brand-text">AI-Chatbot</h2>
                        </a>
                    </li>
                    <li class="nav-item d-md-none">
                        <a class="nav-link open-navbar-container"
                           data-toggle="collapse"
                           data-target="#navbar-mobile">
                            <i class="fa fa-ellipsis-v"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="navbar-container content">
                <div class="collapse navbar-collapse" id="navbar-mobile">
                    <ul class="nav navbar-nav mr-auto float-left">
                        <li class="nav-item d-none d-md-block">
                            <a class="nav-link nav-menu-main menu-toggle hidden-xs" href="javascript:void(0)">
                                <i class="ft-menu"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav float-right">
                        <li class="dropdown dropdown-user nav-item">
                            @await Component.InvokeAsync("DropdownUser")
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!-- ////////////////////////////////////////////////////////////////////////////-->
    <div class="main-menu menu-fixed menu-light menu-accordion menu-shadow"
         data-scroll-to-active="true">
        <div class="main-menu-content">
            @await Component.InvokeAsync("MainMenu");
        </div>
    </div>
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row"></div>
            <div class="content-body">
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- ////////////////////////////////////////////////////////////////////////////-->
    <footer class="footer footer-static footer-light navbar-border">
        <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2">
            <span class="float-md-left d-block d-md-inline-block">
                Copyright &copy; 2022
                <a class="text-bold-800 grey darken-2"
                   href="https://themeforest.net/user/pixinvent/portfolio?ref=pixinvent"
                   target="_blank">HUECIT </a>, All rights reserved.
            </span>
            <!-- <span class="float-md-right d-block d-md-inline-block d-none d-lg-block"
              >Hand-crafted & Made with <i class="ft-heart pink"></i
            ></span> -->
        </p>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.12.1/polyfill.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/exceljs/4.3.0/exceljs.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js"></script>

    <!-- BEGIN VENDOR JS-->
    <script src="~/template-asset/app-assets/vendors/js/vendors.min.js" type="text/javascript"></script>
    <!-- BEGIN VENDOR JS-->
    <script src="~/template-asset/app-assets/vendors/js/tables/jsgrid/jsgrid.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>*@
    <script src="https://unpkg.com/devextreme-quill@1.5.20/dist/dx-quill.min.js"></script>
    <script src="https://cdn3.devexpress.com/jslib/22.1.6/js/dx.all.js"></script>
    @*<script src="~/template-asset/app-assets/vendors/js/charts/raphael-min.js" type="text/javascript"></script>*@
    @*<script src="~/template-asset/app-assets/vendors/js/charts/morris.min.js" type="text/javascript"></script>*@
    <script src="~/template-asset/app-assets/vendors/js/extensions/unslider-min.js" type="text/javascript"></script>
    <script src="~/template-asset/app-assets/vendors/js/forms/select/select2.full.min.js" type="text/javascript"></script>

    <script src="~/template-asset/app-assets/vendors/js/tables/datatable/datatables.min.js" type="text/javascript"></script>
    <!-- BEGIN STACK JS-->
    <script src="~/template-asset/app-assets/js/core/app-menu.js" type="text/javascript"></script>
    <script src="~/template-asset/app-assets/js/core/app.js" type="text/javascript"></script>
    <script src="~/template-asset/app-assets/js/scripts/customizer.js" type="text/javascript"></script>
    <!-- END STACK JS-->

    <script src="~/lib/owl-carousel/js/owl.carousel.min.js" type="text/javascript"></script>

    <script src="~/lib/tree-view-checkbox/dist/tree.js"></script>
    @*<script src="https://js.arcgis.com/4.22/"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>